### ISSUE TITLE
 Is there a way I can change the theme to the way it was before? 

### ISSUE THREAD

**Issue by krek4747** [Riddim-GLiTCH/Virtual-Boy#13]
![Screenshot (27)](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/139050379/c2eabbcd-c29b-4762-9696-15d984c00247)
![Screenshot (28)](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/139050379/9c4be77d-3b38-4de7-a68b-b421b8b473d0)

After I restarted my computer my discord's appearance slightly changed and, well, I don't really like how it looks. Both of those are Eclipse. First screenshot is how it looks now.

**Comment by GH0STP4WZ** [comment]
Are you using Colorways by chance?

**Comment by DaBluLite** [comment]
he is

**Comment by krek4747** [comment]
> Are you using Colorways by chance?

yes, I do. Whenever I pick a bright color, it shows like this. I don't think it did before. Most default themes look different

**Comment by DaBluLite** [comment]
If you are using the plugin, create colorways, or copy existing ones using the Virtual Boy preset
![image](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/73998678/8247b775-aecf-4989-942d-f52e9dbf7db7)

**Comment by GH0STP4WZ** [comment]
> > > Are you using Colorways by chance?
> >
> > yes, I do. Whenever I pick a bright color, it shows like this. I don't think it did before. Most default themes look different
> 
> If you are using the plugin, create colorways, or copy existing ones using the Virtual Boy preset
> ![image](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/73998678/8247b775-aecf-4989-942d-f52e9dbf7db7)

Has this resolved your issue?

**Comment by krek4747** [comment]
> > > > Are you using Colorways by chance?
> > > 
> > > 
> > > yes, I do. Whenever I pick a bright color, it shows like this. I don't think it did before. Most default themes look different
> > 
> > 
> > If you are using the plugin, create colorways, or copy existing ones using the Virtual Boy preset
> > ![image](https://user-images.githubusercontent.com/73998678/255421748-8247b775-aecf-4989-942d-f52e9dbf7db7.png)
> 
> Has this resolved your issue?

I did this and with any too bright color it shows similar pattern like the 1st screenshot which wasnt the case before :(

**Comment by DaBluLite** [comment]
Eclipse works 100% fine with the theme, this also works 100% fine:
```css
/*Automatically Generated - Colorway Creator V1.12 - Preset: Virtual Boy*/
:root {
    --VBaccent: 87 calc(var(--saturation-factor, 1)*85%) 65%;
    --VBaccent-muted: 87 calc(var(--saturation-factor, 1)*85%) 43%;
    --VBaccent-dimmest: 87 calc(var(--saturation-factor, 1)*85%) 33%;
}
```
Here is the Colorway ID as well: 236164663335392c233030303030302c233137313731372c23306130613061

**Comment by krek4747** [comment]
> Eclipse works 100% fine with the theme, this also works 100% fine:
> 
> ```css
> /*Automatically Generated - Colorway Creator V1.12 - Preset: Virtual Boy*/
> :root {
>     --VBaccent: 87 calc(var(--saturation-factor, 1)*85%) 65%;
>     --VBaccent-muted: 87 calc(var(--saturation-factor, 1)*85%) 43%;
>     --VBaccent-dimmest: 87 calc(var(--saturation-factor, 1)*85%) 33%;
> }
> ```
> 
> Here is the Colorway ID as well: 236164663335392c233030303030302c233137313731372c23306130613061

It still looks like the first screenshot. Every time I choose a bright color, it makes the frame of the message darker than the background which wasn't the case before.

**Comment by DaBluLite** [comment]
then just make your own colorway

**Comment by GH0STP4WZ** [comment]
I will admit the colorways update changed how the theme handles colors. Since colorways outputs HSL instead of RGB. If you really want to go back to how it was originally, you can also use
```css
:root {
    --accent (accent in rgb)!important;
    --accent-muted (muted accent in rgb)!important;
   --accent-dimmest (dimmest accent in rgb)!important;
}
```
I left in the ability to use RGB as a fallback, but I'm not sure how the theme will handle it. Also please note that I wrote this comment on my phone, so there's a chance I typoed the handles of the variables.

This may also break transparency, which I plan to add in a future update to fix the visibility of items such as inline timestamps, which currently have a solid background, making them illegible unless you hover over them and read the tool tips instead.

Hope this helps!

**Comment by DaBluLite** [comment]
Truth be told, I would love some feedback on how these colors work, so that I can improve the preset, so please let me know how you think these colors should look like

**Comment by DaBluLite** [comment]
![image](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/73998678/83290b08-42fc-4745-b69e-5cd7c8689581)
this is with a really subtle change in the selection of colors, should I dim the dimmest a bit more?

**Comment by DaBluLite** [comment]
![image](https://github.com/Riddim-GLiTCH/Virtual-Boy/assets/73998678/04f3b2f7-3c93-4698-982f-08f02007de4b)
I think this will be the last iteration of changes for now, pushing with Colorways version 4.0.3

**Comment by DaBluLite** [comment]
The colorway for this iteration is:
```css
/*Automatically Generated - Colorway Creator V1.13 - Preset: Virtual Boy*/
:root {
    --VBaccent: 87 calc(var(--saturation-factor, 1)*87%) 65%;
    --VBaccent-muted: 87 87% 33%;
    --VBaccent-dimmest: 87 87% 19%;
}
```

**Comment by krek4747** [comment]
I made my own colorway that I thought resembled the original Eclipse the most. Here's the ID for it: 233135633631382c233030303030302c233030303030302c23303030303030. Thank you for the help!

**Comment by GH0STP4WZ** [comment]
> Truth be told, I would love some feedback on how these colors work, so that I can improve the preset, so please let me know how you think these colors should look like

I forgot to respond to this. Apologies for that.
It's really simple, actually. The theme uses the three color values we discussed earlier to differenciate between different color intensities. Ideally they would be the shade, but different levels of brightness, however. I have already seen some people mix and mash colors together and it doesn't look too bad. It's really just as you would expect. Accent is the primary accent color. Muted is for muted elements like the inside of a message box or other things that need color but don't need to pop, and dimmest is the same but for things that should be the dimmer than muted. Not sure how else to explain it to be honest.

**Comment by GH0STP4WZ** [comment]
Gonna  mark  this issue as solved but will keep the conversation open in case further discussion  is required.
