### ISSUE TITLE
 change color

### ISSUE THREAD

**Issue by TryNot2Cry** [Riddim-GLiTCH/Virtual-Boy#20]
I can only change my color to white and if you can change it to other colors like blue how ? 
 Unfortunately I don't know much about it :(

**Comment by GH0STP4WZ** [comment]
See [the readme](https://github.com/Riddim-GLiTCH/Virtual-Boy/blob/main/README.md)
Specifically the section __below__ the [part about colorways](https://github.com/Riddim-GLiTCH/Virtual-Boy/blob/main/README.md#note-custom-colorways-work-best-if-the-values-for-primary-secondary-and-tertiary-are-put-to-0)
